environment:
  global:
    PIP_CACHE_DIR: C:\pip_cache

  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

cache:
  - "C:\\pip_cache"

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "SET PATH=%PATH%;C:\\Program\ Files\\Git\\mingw64\\bin"

  # Check that we have the expected version and architecture for Python
  - python --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

build: false  # Not a VS project, build stuff at the test step instead.

test_script:
  - python -m pip install tox codecov
  - tox -e "unit,integration"

on_success:
  - codecov

on_failure:
  - codecov

matrix:
  fast_finish: true
